"""vehicles

Revision ID: 3ce9bcecfcc6
Revises: 24b71b8447ff
Create Date: 2026-08-07 20:44:43.586431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ce9bcecfcc6'
down_revision: Union[str, Sequence[str], None] = '24b71b8447ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workshop_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('plate', sa.String(length=12), nullable=False),
    sa.Column('brand', sa.String(length=60), nullable=True),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workshop_id', 'plate', name='uq_vehicles_taller_patente')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_plate'), ['plate'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_workshop_id'), ['workshop_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_workshop_id'))
        batch_op.drop_index(batch_op.f('ix_vehicles_plate'))
        batch_op.drop_index(batch_op.f('ix_vehicles_client_id'))

    op.drop_table('vehicles')
    # ### end Alembic commands ###
